// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openrtist.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_openrtist_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_openrtist_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_openrtist_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_openrtist_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_openrtist_2eproto;
namespace openrtist {
class Extras;
class ExtrasDefaultTypeInternal;
extern ExtrasDefaultTypeInternal _Extras_default_instance_;
class Extras_ArrowKey;
class Extras_ArrowKeyDefaultTypeInternal;
extern Extras_ArrowKeyDefaultTypeInternal _Extras_ArrowKey_default_instance_;
class Extras_BytesValue;
class Extras_BytesValueDefaultTypeInternal;
extern Extras_BytesValueDefaultTypeInternal _Extras_BytesValue_default_instance_;
class Extras_IMUValue;
class Extras_IMUValueDefaultTypeInternal;
extern Extras_IMUValueDefaultTypeInternal _Extras_IMUValue_default_instance_;
class Extras_ScreenValue;
class Extras_ScreenValueDefaultTypeInternal;
extern Extras_ScreenValueDefaultTypeInternal _Extras_ScreenValue_default_instance_;
class Extras_Setting;
class Extras_SettingDefaultTypeInternal;
extern Extras_SettingDefaultTypeInternal _Extras_Setting_default_instance_;
class Extras_StyleListEntry_DoNotUse;
class Extras_StyleListEntry_DoNotUseDefaultTypeInternal;
extern Extras_StyleListEntry_DoNotUseDefaultTypeInternal _Extras_StyleListEntry_DoNotUse_default_instance_;
class Extras_TouchInput;
class Extras_TouchInputDefaultTypeInternal;
extern Extras_TouchInputDefaultTypeInternal _Extras_TouchInput_default_instance_;
}  // namespace openrtist
PROTOBUF_NAMESPACE_OPEN
template<> ::openrtist::Extras* Arena::CreateMaybeMessage<::openrtist::Extras>(Arena*);
template<> ::openrtist::Extras_ArrowKey* Arena::CreateMaybeMessage<::openrtist::Extras_ArrowKey>(Arena*);
template<> ::openrtist::Extras_BytesValue* Arena::CreateMaybeMessage<::openrtist::Extras_BytesValue>(Arena*);
template<> ::openrtist::Extras_IMUValue* Arena::CreateMaybeMessage<::openrtist::Extras_IMUValue>(Arena*);
template<> ::openrtist::Extras_ScreenValue* Arena::CreateMaybeMessage<::openrtist::Extras_ScreenValue>(Arena*);
template<> ::openrtist::Extras_Setting* Arena::CreateMaybeMessage<::openrtist::Extras_Setting>(Arena*);
template<> ::openrtist::Extras_StyleListEntry_DoNotUse* Arena::CreateMaybeMessage<::openrtist::Extras_StyleListEntry_DoNotUse>(Arena*);
template<> ::openrtist::Extras_TouchInput* Arena::CreateMaybeMessage<::openrtist::Extras_TouchInput>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace openrtist {

// ===================================================================

class Extras_BytesValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.BytesValue) */ {
 public:
  inline Extras_BytesValue() : Extras_BytesValue(nullptr) {};
  virtual ~Extras_BytesValue();

  Extras_BytesValue(const Extras_BytesValue& from);
  Extras_BytesValue(Extras_BytesValue&& from) noexcept
    : Extras_BytesValue() {
    *this = ::std::move(from);
  }

  inline Extras_BytesValue& operator=(const Extras_BytesValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_BytesValue& operator=(Extras_BytesValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_BytesValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_BytesValue* internal_default_instance() {
    return reinterpret_cast<const Extras_BytesValue*>(
               &_Extras_BytesValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Extras_BytesValue& a, Extras_BytesValue& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_BytesValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_BytesValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_BytesValue* New() const final {
    return CreateMaybeMessage<Extras_BytesValue>(nullptr);
  }

  Extras_BytesValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_BytesValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_BytesValue& from);
  void MergeFrom(const Extras_BytesValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_BytesValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.BytesValue";
  }
  protected:
  explicit Extras_BytesValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 1,
  };
  // bytes value = 1;
  void clear_value();
  const std::string& value() const;
  void set_value(const std::string& value);
  void set_value(std::string&& value);
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  std::string* mutable_value();
  std::string* release_value();
  void set_allocated_value(std::string* value);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_value();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_value(
      std::string* value);
  private:
  const std::string& _internal_value() const;
  void _internal_set_value(const std::string& value);
  std::string* _internal_mutable_value();
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.BytesValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_IMUValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.IMUValue) */ {
 public:
  inline Extras_IMUValue() : Extras_IMUValue(nullptr) {};
  virtual ~Extras_IMUValue();

  Extras_IMUValue(const Extras_IMUValue& from);
  Extras_IMUValue(Extras_IMUValue&& from) noexcept
    : Extras_IMUValue() {
    *this = ::std::move(from);
  }

  inline Extras_IMUValue& operator=(const Extras_IMUValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_IMUValue& operator=(Extras_IMUValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_IMUValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_IMUValue* internal_default_instance() {
    return reinterpret_cast<const Extras_IMUValue*>(
               &_Extras_IMUValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Extras_IMUValue& a, Extras_IMUValue& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_IMUValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_IMUValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_IMUValue* New() const final {
    return CreateMaybeMessage<Extras_IMUValue>(nullptr);
  }

  Extras_IMUValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_IMUValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_IMUValue& from);
  void MergeFrom(const Extras_IMUValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_IMUValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.IMUValue";
  }
  protected:
  explicit Extras_IMUValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.IMUValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float x_;
  float y_;
  float z_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_TouchInput PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.TouchInput) */ {
 public:
  inline Extras_TouchInput() : Extras_TouchInput(nullptr) {};
  virtual ~Extras_TouchInput();

  Extras_TouchInput(const Extras_TouchInput& from);
  Extras_TouchInput(Extras_TouchInput&& from) noexcept
    : Extras_TouchInput() {
    *this = ::std::move(from);
  }

  inline Extras_TouchInput& operator=(const Extras_TouchInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_TouchInput& operator=(Extras_TouchInput&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_TouchInput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_TouchInput* internal_default_instance() {
    return reinterpret_cast<const Extras_TouchInput*>(
               &_Extras_TouchInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Extras_TouchInput& a, Extras_TouchInput& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_TouchInput* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_TouchInput* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_TouchInput* New() const final {
    return CreateMaybeMessage<Extras_TouchInput>(nullptr);
  }

  Extras_TouchInput* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_TouchInput>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_TouchInput& from);
  void MergeFrom(const Extras_TouchInput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_TouchInput* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.TouchInput";
  }
  protected:
  explicit Extras_TouchInput(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScaleFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
  };
  // float scale = 1;
  void clear_scale();
  float scale() const;
  void set_scale(float value);
  private:
  float _internal_scale() const;
  void _internal_set_scale(float value);
  public:

  // float x = 2;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 3;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.TouchInput)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float scale_;
  float x_;
  float y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_ScreenValue PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.ScreenValue) */ {
 public:
  inline Extras_ScreenValue() : Extras_ScreenValue(nullptr) {};
  virtual ~Extras_ScreenValue();

  Extras_ScreenValue(const Extras_ScreenValue& from);
  Extras_ScreenValue(Extras_ScreenValue&& from) noexcept
    : Extras_ScreenValue() {
    *this = ::std::move(from);
  }

  inline Extras_ScreenValue& operator=(const Extras_ScreenValue& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_ScreenValue& operator=(Extras_ScreenValue&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_ScreenValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_ScreenValue* internal_default_instance() {
    return reinterpret_cast<const Extras_ScreenValue*>(
               &_Extras_ScreenValue_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Extras_ScreenValue& a, Extras_ScreenValue& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_ScreenValue* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_ScreenValue* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_ScreenValue* New() const final {
    return CreateMaybeMessage<Extras_ScreenValue>(nullptr);
  }

  Extras_ScreenValue* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_ScreenValue>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_ScreenValue& from);
  void MergeFrom(const Extras_ScreenValue& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_ScreenValue* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.ScreenValue";
  }
  protected:
  explicit Extras_ScreenValue(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeightFieldNumber = 1,
    kWidthFieldNumber = 2,
  };
  // int32 height = 1;
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::int32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 width = 2;
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::int32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.ScreenValue)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 height_;
  ::PROTOBUF_NAMESPACE_ID::int32 width_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_ArrowKey PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.ArrowKey) */ {
 public:
  inline Extras_ArrowKey() : Extras_ArrowKey(nullptr) {};
  virtual ~Extras_ArrowKey();

  Extras_ArrowKey(const Extras_ArrowKey& from);
  Extras_ArrowKey(Extras_ArrowKey&& from) noexcept
    : Extras_ArrowKey() {
    *this = ::std::move(from);
  }

  inline Extras_ArrowKey& operator=(const Extras_ArrowKey& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_ArrowKey& operator=(Extras_ArrowKey&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_ArrowKey& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_ArrowKey* internal_default_instance() {
    return reinterpret_cast<const Extras_ArrowKey*>(
               &_Extras_ArrowKey_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Extras_ArrowKey& a, Extras_ArrowKey& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_ArrowKey* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_ArrowKey* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_ArrowKey* New() const final {
    return CreateMaybeMessage<Extras_ArrowKey>(nullptr);
  }

  Extras_ArrowKey* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_ArrowKey>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_ArrowKey& from);
  void MergeFrom(const Extras_ArrowKey& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_ArrowKey* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.ArrowKey";
  }
  protected:
  explicit Extras_ArrowKey(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLeftFieldNumber = 1,
    kRightFieldNumber = 2,
    kUpFieldNumber = 3,
    kDownFieldNumber = 4,
  };
  // bool left = 1;
  void clear_left();
  bool left() const;
  void set_left(bool value);
  private:
  bool _internal_left() const;
  void _internal_set_left(bool value);
  public:

  // bool right = 2;
  void clear_right();
  bool right() const;
  void set_right(bool value);
  private:
  bool _internal_right() const;
  void _internal_set_right(bool value);
  public:

  // bool up = 3;
  void clear_up();
  bool up() const;
  void set_up(bool value);
  private:
  bool _internal_up() const;
  void _internal_set_up(bool value);
  public:

  // bool down = 4;
  void clear_down();
  bool down() const;
  void set_down(bool value);
  private:
  bool _internal_down() const;
  void _internal_set_down(bool value);
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.ArrowKey)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool left_;
  bool right_;
  bool up_;
  bool down_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_Setting PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras.Setting) */ {
 public:
  inline Extras_Setting() : Extras_Setting(nullptr) {};
  virtual ~Extras_Setting();

  Extras_Setting(const Extras_Setting& from);
  Extras_Setting(Extras_Setting&& from) noexcept
    : Extras_Setting() {
    *this = ::std::move(from);
  }

  inline Extras_Setting& operator=(const Extras_Setting& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras_Setting& operator=(Extras_Setting&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras_Setting& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras_Setting* internal_default_instance() {
    return reinterpret_cast<const Extras_Setting*>(
               &_Extras_Setting_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Extras_Setting& a, Extras_Setting& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras_Setting* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras_Setting* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras_Setting* New() const final {
    return CreateMaybeMessage<Extras_Setting>(nullptr);
  }

  Extras_Setting* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras_Setting>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras_Setting& from);
  void MergeFrom(const Extras_Setting& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras_Setting* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras.Setting";
  }
  protected:
  explicit Extras_Setting(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSceneFieldNumber = 1,
    kAlignCenterFieldNumber = 2,
    kArViewFieldNumber = 3,
    kResetFieldNumber = 4,
    kPauseFieldNumber = 5,
    kParticleFieldNumber = 6,
    kInfoFieldNumber = 7,
  };
  // int32 scene = 1;
  void clear_scene();
  ::PROTOBUF_NAMESPACE_ID::int32 scene() const;
  void set_scene(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_scene() const;
  void _internal_set_scene(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // bool align_center = 2;
  void clear_align_center();
  bool align_center() const;
  void set_align_center(bool value);
  private:
  bool _internal_align_center() const;
  void _internal_set_align_center(bool value);
  public:

  // bool ar_view = 3;
  void clear_ar_view();
  bool ar_view() const;
  void set_ar_view(bool value);
  private:
  bool _internal_ar_view() const;
  void _internal_set_ar_view(bool value);
  public:

  // bool reset = 4;
  void clear_reset();
  bool reset() const;
  void set_reset(bool value);
  private:
  bool _internal_reset() const;
  void _internal_set_reset(bool value);
  public:

  // bool pause = 5;
  void clear_pause();
  bool pause() const;
  void set_pause(bool value);
  private:
  bool _internal_pause() const;
  void _internal_set_pause(bool value);
  public:

  // bool particle = 6;
  void clear_particle();
  bool particle() const;
  void set_particle(bool value);
  private:
  bool _internal_particle() const;
  void _internal_set_particle(bool value);
  public:

  // bool info = 7;
  void clear_info();
  bool info() const;
  void set_info(bool value);
  private:
  bool _internal_info() const;
  void _internal_set_info(bool value);
  public:

  // @@protoc_insertion_point(class_scope:openrtist.Extras.Setting)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 scene_;
  bool align_center_;
  bool ar_view_;
  bool reset_;
  bool pause_;
  bool particle_;
  bool info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// -------------------------------------------------------------------

class Extras_StyleListEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Extras_StyleListEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Extras_StyleListEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  Extras_StyleListEntry_DoNotUse();
  Extras_StyleListEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Extras_StyleListEntry_DoNotUse& other);
  static const Extras_StyleListEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Extras_StyleListEntry_DoNotUse*>(&_Extras_StyleListEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "openrtist.Extras.StyleListEntry.key");
 }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "openrtist.Extras.StyleListEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[6];
  }

  public:
};

// -------------------------------------------------------------------

class Extras PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:openrtist.Extras) */ {
 public:
  inline Extras() : Extras(nullptr) {};
  virtual ~Extras();

  Extras(const Extras& from);
  Extras(Extras&& from) noexcept
    : Extras() {
    *this = ::std::move(from);
  }

  inline Extras& operator=(const Extras& from) {
    CopyFrom(from);
    return *this;
  }
  inline Extras& operator=(Extras&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Extras& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Extras* internal_default_instance() {
    return reinterpret_cast<const Extras*>(
               &_Extras_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(Extras& a, Extras& b) {
    a.Swap(&b);
  }
  inline void Swap(Extras* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Extras* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Extras* New() const final {
    return CreateMaybeMessage<Extras>(nullptr);
  }

  Extras* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Extras>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Extras& from);
  void MergeFrom(const Extras& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Extras* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "openrtist.Extras";
  }
  protected:
  explicit Extras(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_openrtist_2eproto);
    return ::descriptor_table_openrtist_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Extras_BytesValue BytesValue;
  typedef Extras_IMUValue IMUValue;
  typedef Extras_TouchInput TouchInput;
  typedef Extras_ScreenValue ScreenValue;
  typedef Extras_ArrowKey ArrowKey;
  typedef Extras_Setting Setting;

  // accessors -------------------------------------------------------

  enum : int {
    kStyleListFieldNumber = 1,
    kImuValueFieldNumber = 2,
    kScreenValueFieldNumber = 3,
    kTouchValueFieldNumber = 4,
    kArrowKeyFieldNumber = 5,
    kSettingValueFieldNumber = 6,
  };
  // map<string, string> style_list = 1;
  int style_list_size() const;
  private:
  int _internal_style_list_size() const;
  public:
  void clear_style_list();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_style_list() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_style_list();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      style_list() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_style_list();

  // .openrtist.Extras.IMUValue imu_value = 2;
  bool has_imu_value() const;
  private:
  bool _internal_has_imu_value() const;
  public:
  void clear_imu_value();
  const ::openrtist::Extras_IMUValue& imu_value() const;
  ::openrtist::Extras_IMUValue* release_imu_value();
  ::openrtist::Extras_IMUValue* mutable_imu_value();
  void set_allocated_imu_value(::openrtist::Extras_IMUValue* imu_value);
  private:
  const ::openrtist::Extras_IMUValue& _internal_imu_value() const;
  ::openrtist::Extras_IMUValue* _internal_mutable_imu_value();
  public:
  void unsafe_arena_set_allocated_imu_value(
      ::openrtist::Extras_IMUValue* imu_value);
  ::openrtist::Extras_IMUValue* unsafe_arena_release_imu_value();

  // .openrtist.Extras.ScreenValue screen_value = 3;
  bool has_screen_value() const;
  private:
  bool _internal_has_screen_value() const;
  public:
  void clear_screen_value();
  const ::openrtist::Extras_ScreenValue& screen_value() const;
  ::openrtist::Extras_ScreenValue* release_screen_value();
  ::openrtist::Extras_ScreenValue* mutable_screen_value();
  void set_allocated_screen_value(::openrtist::Extras_ScreenValue* screen_value);
  private:
  const ::openrtist::Extras_ScreenValue& _internal_screen_value() const;
  ::openrtist::Extras_ScreenValue* _internal_mutable_screen_value();
  public:
  void unsafe_arena_set_allocated_screen_value(
      ::openrtist::Extras_ScreenValue* screen_value);
  ::openrtist::Extras_ScreenValue* unsafe_arena_release_screen_value();

  // .openrtist.Extras.TouchInput touch_value = 4;
  bool has_touch_value() const;
  private:
  bool _internal_has_touch_value() const;
  public:
  void clear_touch_value();
  const ::openrtist::Extras_TouchInput& touch_value() const;
  ::openrtist::Extras_TouchInput* release_touch_value();
  ::openrtist::Extras_TouchInput* mutable_touch_value();
  void set_allocated_touch_value(::openrtist::Extras_TouchInput* touch_value);
  private:
  const ::openrtist::Extras_TouchInput& _internal_touch_value() const;
  ::openrtist::Extras_TouchInput* _internal_mutable_touch_value();
  public:
  void unsafe_arena_set_allocated_touch_value(
      ::openrtist::Extras_TouchInput* touch_value);
  ::openrtist::Extras_TouchInput* unsafe_arena_release_touch_value();

  // .openrtist.Extras.ArrowKey arrow_key = 5;
  bool has_arrow_key() const;
  private:
  bool _internal_has_arrow_key() const;
  public:
  void clear_arrow_key();
  const ::openrtist::Extras_ArrowKey& arrow_key() const;
  ::openrtist::Extras_ArrowKey* release_arrow_key();
  ::openrtist::Extras_ArrowKey* mutable_arrow_key();
  void set_allocated_arrow_key(::openrtist::Extras_ArrowKey* arrow_key);
  private:
  const ::openrtist::Extras_ArrowKey& _internal_arrow_key() const;
  ::openrtist::Extras_ArrowKey* _internal_mutable_arrow_key();
  public:
  void unsafe_arena_set_allocated_arrow_key(
      ::openrtist::Extras_ArrowKey* arrow_key);
  ::openrtist::Extras_ArrowKey* unsafe_arena_release_arrow_key();

  // .openrtist.Extras.Setting setting_value = 6;
  bool has_setting_value() const;
  private:
  bool _internal_has_setting_value() const;
  public:
  void clear_setting_value();
  const ::openrtist::Extras_Setting& setting_value() const;
  ::openrtist::Extras_Setting* release_setting_value();
  ::openrtist::Extras_Setting* mutable_setting_value();
  void set_allocated_setting_value(::openrtist::Extras_Setting* setting_value);
  private:
  const ::openrtist::Extras_Setting& _internal_setting_value() const;
  ::openrtist::Extras_Setting* _internal_mutable_setting_value();
  public:
  void unsafe_arena_set_allocated_setting_value(
      ::openrtist::Extras_Setting* setting_value);
  ::openrtist::Extras_Setting* unsafe_arena_release_setting_value();

  // @@protoc_insertion_point(class_scope:openrtist.Extras)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Extras_StyleListEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > style_list_;
  ::openrtist::Extras_IMUValue* imu_value_;
  ::openrtist::Extras_ScreenValue* screen_value_;
  ::openrtist::Extras_TouchInput* touch_value_;
  ::openrtist::Extras_ArrowKey* arrow_key_;
  ::openrtist::Extras_Setting* setting_value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_openrtist_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Extras_BytesValue

// bytes value = 1;
inline void Extras_BytesValue::clear_value() {
  value_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Extras_BytesValue::value() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.BytesValue.value)
  return _internal_value();
}
inline void Extras_BytesValue::set_value(const std::string& value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.BytesValue.value)
}
inline std::string* Extras_BytesValue::mutable_value() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.BytesValue.value)
  return _internal_mutable_value();
}
inline const std::string& Extras_BytesValue::_internal_value() const {
  return value_.Get();
}
inline void Extras_BytesValue::_internal_set_value(const std::string& value) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Extras_BytesValue::set_value(std::string&& value) {
  
  value_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:openrtist.Extras.BytesValue.value)
}
inline void Extras_BytesValue::set_value(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:openrtist.Extras.BytesValue.value)
}
inline void Extras_BytesValue::set_value(const void* value,
    size_t size) {
  
  value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:openrtist.Extras.BytesValue.value)
}
inline std::string* Extras_BytesValue::_internal_mutable_value() {
  
  return value_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Extras_BytesValue::release_value() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.BytesValue.value)
  return value_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Extras_BytesValue::set_allocated_value(std::string* value) {
  if (value != nullptr) {
    
  } else {
    
  }
  value_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.BytesValue.value)
}
inline std::string* Extras_BytesValue::unsafe_arena_release_value() {
  // @@protoc_insertion_point(field_unsafe_arena_release:openrtist.Extras.BytesValue.value)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return value_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Extras_BytesValue::unsafe_arena_set_allocated_value(
    std::string* value) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (value != nullptr) {
    
  } else {
    
  }
  value_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      value, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.BytesValue.value)
}

// -------------------------------------------------------------------

// Extras_IMUValue

// float x = 1;
inline void Extras_IMUValue::clear_x() {
  x_ = 0;
}
inline float Extras_IMUValue::_internal_x() const {
  return x_;
}
inline float Extras_IMUValue::x() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.IMUValue.x)
  return _internal_x();
}
inline void Extras_IMUValue::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Extras_IMUValue::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.IMUValue.x)
}

// float y = 2;
inline void Extras_IMUValue::clear_y() {
  y_ = 0;
}
inline float Extras_IMUValue::_internal_y() const {
  return y_;
}
inline float Extras_IMUValue::y() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.IMUValue.y)
  return _internal_y();
}
inline void Extras_IMUValue::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Extras_IMUValue::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.IMUValue.y)
}

// float z = 3;
inline void Extras_IMUValue::clear_z() {
  z_ = 0;
}
inline float Extras_IMUValue::_internal_z() const {
  return z_;
}
inline float Extras_IMUValue::z() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.IMUValue.z)
  return _internal_z();
}
inline void Extras_IMUValue::_internal_set_z(float value) {
  
  z_ = value;
}
inline void Extras_IMUValue::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.IMUValue.z)
}

// -------------------------------------------------------------------

// Extras_TouchInput

// float scale = 1;
inline void Extras_TouchInput::clear_scale() {
  scale_ = 0;
}
inline float Extras_TouchInput::_internal_scale() const {
  return scale_;
}
inline float Extras_TouchInput::scale() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.TouchInput.scale)
  return _internal_scale();
}
inline void Extras_TouchInput::_internal_set_scale(float value) {
  
  scale_ = value;
}
inline void Extras_TouchInput::set_scale(float value) {
  _internal_set_scale(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.TouchInput.scale)
}

// float x = 2;
inline void Extras_TouchInput::clear_x() {
  x_ = 0;
}
inline float Extras_TouchInput::_internal_x() const {
  return x_;
}
inline float Extras_TouchInput::x() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.TouchInput.x)
  return _internal_x();
}
inline void Extras_TouchInput::_internal_set_x(float value) {
  
  x_ = value;
}
inline void Extras_TouchInput::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.TouchInput.x)
}

// float y = 3;
inline void Extras_TouchInput::clear_y() {
  y_ = 0;
}
inline float Extras_TouchInput::_internal_y() const {
  return y_;
}
inline float Extras_TouchInput::y() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.TouchInput.y)
  return _internal_y();
}
inline void Extras_TouchInput::_internal_set_y(float value) {
  
  y_ = value;
}
inline void Extras_TouchInput::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.TouchInput.y)
}

// -------------------------------------------------------------------

// Extras_ScreenValue

// int32 height = 1;
inline void Extras_ScreenValue::clear_height() {
  height_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_ScreenValue::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_ScreenValue::height() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ScreenValue.height)
  return _internal_height();
}
inline void Extras_ScreenValue::_internal_set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  height_ = value;
}
inline void Extras_ScreenValue::set_height(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ScreenValue.height)
}

// int32 width = 2;
inline void Extras_ScreenValue::clear_width() {
  width_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_ScreenValue::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_ScreenValue::width() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ScreenValue.width)
  return _internal_width();
}
inline void Extras_ScreenValue::_internal_set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  width_ = value;
}
inline void Extras_ScreenValue::set_width(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ScreenValue.width)
}

// -------------------------------------------------------------------

// Extras_ArrowKey

// bool left = 1;
inline void Extras_ArrowKey::clear_left() {
  left_ = false;
}
inline bool Extras_ArrowKey::_internal_left() const {
  return left_;
}
inline bool Extras_ArrowKey::left() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ArrowKey.left)
  return _internal_left();
}
inline void Extras_ArrowKey::_internal_set_left(bool value) {
  
  left_ = value;
}
inline void Extras_ArrowKey::set_left(bool value) {
  _internal_set_left(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ArrowKey.left)
}

// bool right = 2;
inline void Extras_ArrowKey::clear_right() {
  right_ = false;
}
inline bool Extras_ArrowKey::_internal_right() const {
  return right_;
}
inline bool Extras_ArrowKey::right() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ArrowKey.right)
  return _internal_right();
}
inline void Extras_ArrowKey::_internal_set_right(bool value) {
  
  right_ = value;
}
inline void Extras_ArrowKey::set_right(bool value) {
  _internal_set_right(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ArrowKey.right)
}

// bool up = 3;
inline void Extras_ArrowKey::clear_up() {
  up_ = false;
}
inline bool Extras_ArrowKey::_internal_up() const {
  return up_;
}
inline bool Extras_ArrowKey::up() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ArrowKey.up)
  return _internal_up();
}
inline void Extras_ArrowKey::_internal_set_up(bool value) {
  
  up_ = value;
}
inline void Extras_ArrowKey::set_up(bool value) {
  _internal_set_up(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ArrowKey.up)
}

// bool down = 4;
inline void Extras_ArrowKey::clear_down() {
  down_ = false;
}
inline bool Extras_ArrowKey::_internal_down() const {
  return down_;
}
inline bool Extras_ArrowKey::down() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.ArrowKey.down)
  return _internal_down();
}
inline void Extras_ArrowKey::_internal_set_down(bool value) {
  
  down_ = value;
}
inline void Extras_ArrowKey::set_down(bool value) {
  _internal_set_down(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.ArrowKey.down)
}

// -------------------------------------------------------------------

// Extras_Setting

// int32 scene = 1;
inline void Extras_Setting::clear_scene() {
  scene_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_Setting::_internal_scene() const {
  return scene_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Extras_Setting::scene() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.scene)
  return _internal_scene();
}
inline void Extras_Setting::_internal_set_scene(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  scene_ = value;
}
inline void Extras_Setting::set_scene(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_scene(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.scene)
}

// bool align_center = 2;
inline void Extras_Setting::clear_align_center() {
  align_center_ = false;
}
inline bool Extras_Setting::_internal_align_center() const {
  return align_center_;
}
inline bool Extras_Setting::align_center() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.align_center)
  return _internal_align_center();
}
inline void Extras_Setting::_internal_set_align_center(bool value) {
  
  align_center_ = value;
}
inline void Extras_Setting::set_align_center(bool value) {
  _internal_set_align_center(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.align_center)
}

// bool ar_view = 3;
inline void Extras_Setting::clear_ar_view() {
  ar_view_ = false;
}
inline bool Extras_Setting::_internal_ar_view() const {
  return ar_view_;
}
inline bool Extras_Setting::ar_view() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.ar_view)
  return _internal_ar_view();
}
inline void Extras_Setting::_internal_set_ar_view(bool value) {
  
  ar_view_ = value;
}
inline void Extras_Setting::set_ar_view(bool value) {
  _internal_set_ar_view(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.ar_view)
}

// bool reset = 4;
inline void Extras_Setting::clear_reset() {
  reset_ = false;
}
inline bool Extras_Setting::_internal_reset() const {
  return reset_;
}
inline bool Extras_Setting::reset() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.reset)
  return _internal_reset();
}
inline void Extras_Setting::_internal_set_reset(bool value) {
  
  reset_ = value;
}
inline void Extras_Setting::set_reset(bool value) {
  _internal_set_reset(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.reset)
}

// bool pause = 5;
inline void Extras_Setting::clear_pause() {
  pause_ = false;
}
inline bool Extras_Setting::_internal_pause() const {
  return pause_;
}
inline bool Extras_Setting::pause() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.pause)
  return _internal_pause();
}
inline void Extras_Setting::_internal_set_pause(bool value) {
  
  pause_ = value;
}
inline void Extras_Setting::set_pause(bool value) {
  _internal_set_pause(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.pause)
}

// bool particle = 6;
inline void Extras_Setting::clear_particle() {
  particle_ = false;
}
inline bool Extras_Setting::_internal_particle() const {
  return particle_;
}
inline bool Extras_Setting::particle() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.particle)
  return _internal_particle();
}
inline void Extras_Setting::_internal_set_particle(bool value) {
  
  particle_ = value;
}
inline void Extras_Setting::set_particle(bool value) {
  _internal_set_particle(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.particle)
}

// bool info = 7;
inline void Extras_Setting::clear_info() {
  info_ = false;
}
inline bool Extras_Setting::_internal_info() const {
  return info_;
}
inline bool Extras_Setting::info() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.Setting.info)
  return _internal_info();
}
inline void Extras_Setting::_internal_set_info(bool value) {
  
  info_ = value;
}
inline void Extras_Setting::set_info(bool value) {
  _internal_set_info(value);
  // @@protoc_insertion_point(field_set:openrtist.Extras.Setting.info)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// Extras

// map<string, string> style_list = 1;
inline int Extras::_internal_style_list_size() const {
  return style_list_.size();
}
inline int Extras::style_list_size() const {
  return _internal_style_list_size();
}
inline void Extras::clear_style_list() {
  style_list_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Extras::_internal_style_list() const {
  return style_list_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
Extras::style_list() const {
  // @@protoc_insertion_point(field_map:openrtist.Extras.style_list)
  return _internal_style_list();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Extras::_internal_mutable_style_list() {
  return style_list_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
Extras::mutable_style_list() {
  // @@protoc_insertion_point(field_mutable_map:openrtist.Extras.style_list)
  return _internal_mutable_style_list();
}

// .openrtist.Extras.IMUValue imu_value = 2;
inline bool Extras::_internal_has_imu_value() const {
  return this != internal_default_instance() && imu_value_ != nullptr;
}
inline bool Extras::has_imu_value() const {
  return _internal_has_imu_value();
}
inline void Extras::clear_imu_value() {
  if (GetArena() == nullptr && imu_value_ != nullptr) {
    delete imu_value_;
  }
  imu_value_ = nullptr;
}
inline const ::openrtist::Extras_IMUValue& Extras::_internal_imu_value() const {
  const ::openrtist::Extras_IMUValue* p = imu_value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openrtist::Extras_IMUValue*>(
      &::openrtist::_Extras_IMUValue_default_instance_);
}
inline const ::openrtist::Extras_IMUValue& Extras::imu_value() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.imu_value)
  return _internal_imu_value();
}
inline void Extras::unsafe_arena_set_allocated_imu_value(
    ::openrtist::Extras_IMUValue* imu_value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(imu_value_);
  }
  imu_value_ = imu_value;
  if (imu_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.imu_value)
}
inline ::openrtist::Extras_IMUValue* Extras::release_imu_value() {
  auto temp = unsafe_arena_release_imu_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openrtist::Extras_IMUValue* Extras::unsafe_arena_release_imu_value() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.imu_value)
  
  ::openrtist::Extras_IMUValue* temp = imu_value_;
  imu_value_ = nullptr;
  return temp;
}
inline ::openrtist::Extras_IMUValue* Extras::_internal_mutable_imu_value() {
  
  if (imu_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::openrtist::Extras_IMUValue>(GetArena());
    imu_value_ = p;
  }
  return imu_value_;
}
inline ::openrtist::Extras_IMUValue* Extras::mutable_imu_value() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.imu_value)
  return _internal_mutable_imu_value();
}
inline void Extras::set_allocated_imu_value(::openrtist::Extras_IMUValue* imu_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete imu_value_;
  }
  if (imu_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(imu_value);
    if (message_arena != submessage_arena) {
      imu_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, imu_value, submessage_arena);
    }
    
  } else {
    
  }
  imu_value_ = imu_value;
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.imu_value)
}

// .openrtist.Extras.ScreenValue screen_value = 3;
inline bool Extras::_internal_has_screen_value() const {
  return this != internal_default_instance() && screen_value_ != nullptr;
}
inline bool Extras::has_screen_value() const {
  return _internal_has_screen_value();
}
inline void Extras::clear_screen_value() {
  if (GetArena() == nullptr && screen_value_ != nullptr) {
    delete screen_value_;
  }
  screen_value_ = nullptr;
}
inline const ::openrtist::Extras_ScreenValue& Extras::_internal_screen_value() const {
  const ::openrtist::Extras_ScreenValue* p = screen_value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openrtist::Extras_ScreenValue*>(
      &::openrtist::_Extras_ScreenValue_default_instance_);
}
inline const ::openrtist::Extras_ScreenValue& Extras::screen_value() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.screen_value)
  return _internal_screen_value();
}
inline void Extras::unsafe_arena_set_allocated_screen_value(
    ::openrtist::Extras_ScreenValue* screen_value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(screen_value_);
  }
  screen_value_ = screen_value;
  if (screen_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.screen_value)
}
inline ::openrtist::Extras_ScreenValue* Extras::release_screen_value() {
  auto temp = unsafe_arena_release_screen_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openrtist::Extras_ScreenValue* Extras::unsafe_arena_release_screen_value() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.screen_value)
  
  ::openrtist::Extras_ScreenValue* temp = screen_value_;
  screen_value_ = nullptr;
  return temp;
}
inline ::openrtist::Extras_ScreenValue* Extras::_internal_mutable_screen_value() {
  
  if (screen_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::openrtist::Extras_ScreenValue>(GetArena());
    screen_value_ = p;
  }
  return screen_value_;
}
inline ::openrtist::Extras_ScreenValue* Extras::mutable_screen_value() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.screen_value)
  return _internal_mutable_screen_value();
}
inline void Extras::set_allocated_screen_value(::openrtist::Extras_ScreenValue* screen_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete screen_value_;
  }
  if (screen_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(screen_value);
    if (message_arena != submessage_arena) {
      screen_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, screen_value, submessage_arena);
    }
    
  } else {
    
  }
  screen_value_ = screen_value;
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.screen_value)
}

// .openrtist.Extras.TouchInput touch_value = 4;
inline bool Extras::_internal_has_touch_value() const {
  return this != internal_default_instance() && touch_value_ != nullptr;
}
inline bool Extras::has_touch_value() const {
  return _internal_has_touch_value();
}
inline void Extras::clear_touch_value() {
  if (GetArena() == nullptr && touch_value_ != nullptr) {
    delete touch_value_;
  }
  touch_value_ = nullptr;
}
inline const ::openrtist::Extras_TouchInput& Extras::_internal_touch_value() const {
  const ::openrtist::Extras_TouchInput* p = touch_value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openrtist::Extras_TouchInput*>(
      &::openrtist::_Extras_TouchInput_default_instance_);
}
inline const ::openrtist::Extras_TouchInput& Extras::touch_value() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.touch_value)
  return _internal_touch_value();
}
inline void Extras::unsafe_arena_set_allocated_touch_value(
    ::openrtist::Extras_TouchInput* touch_value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(touch_value_);
  }
  touch_value_ = touch_value;
  if (touch_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.touch_value)
}
inline ::openrtist::Extras_TouchInput* Extras::release_touch_value() {
  auto temp = unsafe_arena_release_touch_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openrtist::Extras_TouchInput* Extras::unsafe_arena_release_touch_value() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.touch_value)
  
  ::openrtist::Extras_TouchInput* temp = touch_value_;
  touch_value_ = nullptr;
  return temp;
}
inline ::openrtist::Extras_TouchInput* Extras::_internal_mutable_touch_value() {
  
  if (touch_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::openrtist::Extras_TouchInput>(GetArena());
    touch_value_ = p;
  }
  return touch_value_;
}
inline ::openrtist::Extras_TouchInput* Extras::mutable_touch_value() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.touch_value)
  return _internal_mutable_touch_value();
}
inline void Extras::set_allocated_touch_value(::openrtist::Extras_TouchInput* touch_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete touch_value_;
  }
  if (touch_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(touch_value);
    if (message_arena != submessage_arena) {
      touch_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, touch_value, submessage_arena);
    }
    
  } else {
    
  }
  touch_value_ = touch_value;
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.touch_value)
}

// .openrtist.Extras.ArrowKey arrow_key = 5;
inline bool Extras::_internal_has_arrow_key() const {
  return this != internal_default_instance() && arrow_key_ != nullptr;
}
inline bool Extras::has_arrow_key() const {
  return _internal_has_arrow_key();
}
inline void Extras::clear_arrow_key() {
  if (GetArena() == nullptr && arrow_key_ != nullptr) {
    delete arrow_key_;
  }
  arrow_key_ = nullptr;
}
inline const ::openrtist::Extras_ArrowKey& Extras::_internal_arrow_key() const {
  const ::openrtist::Extras_ArrowKey* p = arrow_key_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openrtist::Extras_ArrowKey*>(
      &::openrtist::_Extras_ArrowKey_default_instance_);
}
inline const ::openrtist::Extras_ArrowKey& Extras::arrow_key() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.arrow_key)
  return _internal_arrow_key();
}
inline void Extras::unsafe_arena_set_allocated_arrow_key(
    ::openrtist::Extras_ArrowKey* arrow_key) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(arrow_key_);
  }
  arrow_key_ = arrow_key;
  if (arrow_key) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.arrow_key)
}
inline ::openrtist::Extras_ArrowKey* Extras::release_arrow_key() {
  auto temp = unsafe_arena_release_arrow_key();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openrtist::Extras_ArrowKey* Extras::unsafe_arena_release_arrow_key() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.arrow_key)
  
  ::openrtist::Extras_ArrowKey* temp = arrow_key_;
  arrow_key_ = nullptr;
  return temp;
}
inline ::openrtist::Extras_ArrowKey* Extras::_internal_mutable_arrow_key() {
  
  if (arrow_key_ == nullptr) {
    auto* p = CreateMaybeMessage<::openrtist::Extras_ArrowKey>(GetArena());
    arrow_key_ = p;
  }
  return arrow_key_;
}
inline ::openrtist::Extras_ArrowKey* Extras::mutable_arrow_key() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.arrow_key)
  return _internal_mutable_arrow_key();
}
inline void Extras::set_allocated_arrow_key(::openrtist::Extras_ArrowKey* arrow_key) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete arrow_key_;
  }
  if (arrow_key) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(arrow_key);
    if (message_arena != submessage_arena) {
      arrow_key = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, arrow_key, submessage_arena);
    }
    
  } else {
    
  }
  arrow_key_ = arrow_key;
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.arrow_key)
}

// .openrtist.Extras.Setting setting_value = 6;
inline bool Extras::_internal_has_setting_value() const {
  return this != internal_default_instance() && setting_value_ != nullptr;
}
inline bool Extras::has_setting_value() const {
  return _internal_has_setting_value();
}
inline void Extras::clear_setting_value() {
  if (GetArena() == nullptr && setting_value_ != nullptr) {
    delete setting_value_;
  }
  setting_value_ = nullptr;
}
inline const ::openrtist::Extras_Setting& Extras::_internal_setting_value() const {
  const ::openrtist::Extras_Setting* p = setting_value_;
  return p != nullptr ? *p : *reinterpret_cast<const ::openrtist::Extras_Setting*>(
      &::openrtist::_Extras_Setting_default_instance_);
}
inline const ::openrtist::Extras_Setting& Extras::setting_value() const {
  // @@protoc_insertion_point(field_get:openrtist.Extras.setting_value)
  return _internal_setting_value();
}
inline void Extras::unsafe_arena_set_allocated_setting_value(
    ::openrtist::Extras_Setting* setting_value) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(setting_value_);
  }
  setting_value_ = setting_value;
  if (setting_value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:openrtist.Extras.setting_value)
}
inline ::openrtist::Extras_Setting* Extras::release_setting_value() {
  auto temp = unsafe_arena_release_setting_value();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::openrtist::Extras_Setting* Extras::unsafe_arena_release_setting_value() {
  // @@protoc_insertion_point(field_release:openrtist.Extras.setting_value)
  
  ::openrtist::Extras_Setting* temp = setting_value_;
  setting_value_ = nullptr;
  return temp;
}
inline ::openrtist::Extras_Setting* Extras::_internal_mutable_setting_value() {
  
  if (setting_value_ == nullptr) {
    auto* p = CreateMaybeMessage<::openrtist::Extras_Setting>(GetArena());
    setting_value_ = p;
  }
  return setting_value_;
}
inline ::openrtist::Extras_Setting* Extras::mutable_setting_value() {
  // @@protoc_insertion_point(field_mutable:openrtist.Extras.setting_value)
  return _internal_mutable_setting_value();
}
inline void Extras::set_allocated_setting_value(::openrtist::Extras_Setting* setting_value) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete setting_value_;
  }
  if (setting_value) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(setting_value);
    if (message_arena != submessage_arena) {
      setting_value = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, setting_value, submessage_arena);
    }
    
  } else {
    
  }
  setting_value_ = setting_value;
  // @@protoc_insertion_point(field_set_allocated:openrtist.Extras.setting_value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace openrtist

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_openrtist_2eproto
