// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfluid.proto

#include "openfluid.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_ArrowKey_openfluid_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_IMUValue_openfluid_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_ScreenValue_openfluid_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_Setting_openfluid_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_openfluid_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_TouchInput_openfluid_2eproto;
namespace openfluid {
class Extras_BytesValueDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_BytesValue> _instance;
} _Extras_BytesValue_default_instance_;
class Extras_IMUValueDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_IMUValue> _instance;
} _Extras_IMUValue_default_instance_;
class Extras_TouchInputDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_TouchInput> _instance;
} _Extras_TouchInput_default_instance_;
class Extras_ScreenValueDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_ScreenValue> _instance;
} _Extras_ScreenValue_default_instance_;
class Extras_ArrowKeyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_ArrowKey> _instance;
} _Extras_ArrowKey_default_instance_;
class Extras_SettingDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_Setting> _instance;
} _Extras_Setting_default_instance_;
class Extras_StyleListEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras_StyleListEntry_DoNotUse> _instance;
} _Extras_StyleListEntry_DoNotUse_default_instance_;
class ExtrasDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Extras> _instance;
} _Extras_default_instance_;
}  // namespace openfluid
static void InitDefaultsscc_info_Extras_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_default_instance_;
    new (ptr) ::openfluid::Extras();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<6> scc_info_Extras_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 6, 0, InitDefaultsscc_info_Extras_openfluid_2eproto}, {
      &scc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto.base,
      &scc_info_Extras_IMUValue_openfluid_2eproto.base,
      &scc_info_Extras_ScreenValue_openfluid_2eproto.base,
      &scc_info_Extras_TouchInput_openfluid_2eproto.base,
      &scc_info_Extras_ArrowKey_openfluid_2eproto.base,
      &scc_info_Extras_Setting_openfluid_2eproto.base,}};

static void InitDefaultsscc_info_Extras_ArrowKey_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_ArrowKey_default_instance_;
    new (ptr) ::openfluid::Extras_ArrowKey();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_ArrowKey::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_ArrowKey_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_ArrowKey_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_BytesValue_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_BytesValue_default_instance_;
    new (ptr) ::openfluid::Extras_BytesValue();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_BytesValue::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_BytesValue_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_BytesValue_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_IMUValue_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_IMUValue_default_instance_;
    new (ptr) ::openfluid::Extras_IMUValue();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_IMUValue::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_IMUValue_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_IMUValue_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_ScreenValue_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_ScreenValue_default_instance_;
    new (ptr) ::openfluid::Extras_ScreenValue();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_ScreenValue::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_ScreenValue_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_ScreenValue_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_Setting_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_Setting_default_instance_;
    new (ptr) ::openfluid::Extras_Setting();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_Setting::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_Setting_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_Setting_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_StyleListEntry_DoNotUse_default_instance_;
    new (ptr) ::openfluid::Extras_StyleListEntry_DoNotUse();
  }
  ::openfluid::Extras_StyleListEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto}, {}};

static void InitDefaultsscc_info_Extras_TouchInput_openfluid_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::openfluid::_Extras_TouchInput_default_instance_;
    new (ptr) ::openfluid::Extras_TouchInput();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::openfluid::Extras_TouchInput::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Extras_TouchInput_openfluid_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Extras_TouchInput_openfluid_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_openfluid_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_openfluid_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_openfluid_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_openfluid_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_BytesValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_BytesValue, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_IMUValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_IMUValue, x_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_IMUValue, y_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_IMUValue, z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_TouchInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_TouchInput, scale_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_TouchInput, x_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_TouchInput, y_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_TouchInput, doubletouch_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ScreenValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ScreenValue, ratio_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ScreenValue, resolution_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ArrowKey, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ArrowKey, left_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ArrowKey, right_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ArrowKey, up_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_ArrowKey, down_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, scene_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, align_center_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, ar_view_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, reset_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, pause_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, particle_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_Setting, info_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_StyleListEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_StyleListEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_StyleListEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras_StyleListEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, style_list_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, imu_value_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, screen_value_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, touch_value_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, arrow_key_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, setting_value_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, latency_token_),
  PROTOBUF_FIELD_OFFSET(::openfluid::Extras, fps_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::openfluid::Extras_BytesValue)},
  { 6, -1, sizeof(::openfluid::Extras_IMUValue)},
  { 14, -1, sizeof(::openfluid::Extras_TouchInput)},
  { 23, -1, sizeof(::openfluid::Extras_ScreenValue)},
  { 30, -1, sizeof(::openfluid::Extras_ArrowKey)},
  { 39, -1, sizeof(::openfluid::Extras_Setting)},
  { 51, 58, sizeof(::openfluid::Extras_StyleListEntry_DoNotUse)},
  { 60, -1, sizeof(::openfluid::Extras)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_BytesValue_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_IMUValue_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_TouchInput_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_ScreenValue_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_ArrowKey_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_Setting_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_StyleListEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::openfluid::_Extras_default_instance_),
};

const char descriptor_table_protodef_openfluid_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017openfluid.proto\022\topenfluid\"\222\006\n\006Extras\022"
  "4\n\nstyle_list\030\001 \003(\0132 .openfluid.Extras.S"
  "tyleListEntry\022-\n\timu_value\030\002 \001(\0132\032.openf"
  "luid.Extras.IMUValue\0223\n\014screen_value\030\003 \001"
  "(\0132\035.openfluid.Extras.ScreenValue\0221\n\013tou"
  "ch_value\030\004 \001(\0132\034.openfluid.Extras.TouchI"
  "nput\022-\n\tarrow_key\030\005 \001(\0132\032.openfluid.Extr"
  "as.ArrowKey\0220\n\rsetting_value\030\006 \001(\0132\031.ope"
  "nfluid.Extras.Setting\022\025\n\rlatency_token\030\007"
  " \001(\010\022\013\n\003fps\030\010 \001(\005\032\033\n\nBytesValue\022\r\n\005value"
  "\030\001 \001(\014\032+\n\010IMUValue\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002"
  "\022\t\n\001z\030\003 \001(\002\032F\n\nTouchInput\022\r\n\005scale\030\001 \001(\002"
  "\022\t\n\001x\030\002 \001(\002\022\t\n\001y\030\003 \001(\002\022\023\n\013doubleTouch\030\004 "
  "\001(\010\0320\n\013ScreenValue\022\r\n\005ratio\030\001 \001(\002\022\022\n\nres"
  "olution\030\002 \001(\005\032A\n\010ArrowKey\022\014\n\004left\030\001 \001(\010\022"
  "\r\n\005right\030\002 \001(\010\022\n\n\002up\030\003 \001(\010\022\014\n\004down\030\004 \001(\010"
  "\032}\n\007Setting\022\r\n\005scene\030\001 \001(\005\022\024\n\014align_cent"
  "er\030\002 \001(\010\022\017\n\007ar_view\030\003 \001(\010\022\r\n\005reset\030\004 \001(\010"
  "\022\r\n\005pause\030\005 \001(\010\022\020\n\010particle\030\006 \001(\010\022\014\n\004inf"
  "o\030\007 \001(\010\0320\n\016StyleListEntry\022\013\n\003key\030\001 \001(\t\022\r"
  "\n\005value\030\002 \001(\t:\0028\001B\036\n\024edu.cmu.cs.openflui"
  "dB\006Protosb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_openfluid_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_openfluid_2eproto_sccs[8] = {
  &scc_info_Extras_openfluid_2eproto.base,
  &scc_info_Extras_ArrowKey_openfluid_2eproto.base,
  &scc_info_Extras_BytesValue_openfluid_2eproto.base,
  &scc_info_Extras_IMUValue_openfluid_2eproto.base,
  &scc_info_Extras_ScreenValue_openfluid_2eproto.base,
  &scc_info_Extras_Setting_openfluid_2eproto.base,
  &scc_info_Extras_StyleListEntry_DoNotUse_openfluid_2eproto.base,
  &scc_info_Extras_TouchInput_openfluid_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_openfluid_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_openfluid_2eproto = {
  false, false, descriptor_table_protodef_openfluid_2eproto, "openfluid.proto", 857,
  &descriptor_table_openfluid_2eproto_once, descriptor_table_openfluid_2eproto_sccs, descriptor_table_openfluid_2eproto_deps, 8, 0,
  schemas, file_default_instances, TableStruct_openfluid_2eproto::offsets,
  file_level_metadata_openfluid_2eproto, 8, file_level_enum_descriptors_openfluid_2eproto, file_level_service_descriptors_openfluid_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_openfluid_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_openfluid_2eproto)), true);
namespace openfluid {

// ===================================================================

void Extras_BytesValue::InitAsDefaultInstance() {
}
class Extras_BytesValue::_Internal {
 public:
};

Extras_BytesValue::Extras_BytesValue(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.BytesValue)
}
Extras_BytesValue::Extras_BytesValue(const Extras_BytesValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_value().empty()) {
    value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_value(),
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.BytesValue)
}

void Extras_BytesValue::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Extras_BytesValue_openfluid_2eproto.base);
  value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

Extras_BytesValue::~Extras_BytesValue() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.BytesValue)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_BytesValue::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  value_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Extras_BytesValue::ArenaDtor(void* object) {
  Extras_BytesValue* _this = reinterpret_cast< Extras_BytesValue* >(object);
  (void)_this;
}
void Extras_BytesValue::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_BytesValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_BytesValue& Extras_BytesValue::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_BytesValue_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_BytesValue::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.BytesValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  value_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_BytesValue::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_BytesValue::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.BytesValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes value = 1;
  if (this->value().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.BytesValue)
  return target;
}

size_t Extras_BytesValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.BytesValue)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes value = 1;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_value());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_BytesValue::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.BytesValue)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_BytesValue* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_BytesValue>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.BytesValue)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.BytesValue)
    MergeFrom(*source);
  }
}

void Extras_BytesValue::MergeFrom(const Extras_BytesValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.BytesValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value().size() > 0) {
    _internal_set_value(from._internal_value());
  }
}

void Extras_BytesValue::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.BytesValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_BytesValue::CopyFrom(const Extras_BytesValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.BytesValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_BytesValue::IsInitialized() const {
  return true;
}

void Extras_BytesValue::InternalSwap(Extras_BytesValue* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  value_.Swap(&other->value_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_BytesValue::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Extras_IMUValue::InitAsDefaultInstance() {
}
class Extras_IMUValue::_Internal {
 public:
};

Extras_IMUValue::Extras_IMUValue(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.IMUValue)
}
Extras_IMUValue::Extras_IMUValue(const Extras_IMUValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.IMUValue)
}

void Extras_IMUValue::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

Extras_IMUValue::~Extras_IMUValue() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.IMUValue)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_IMUValue::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Extras_IMUValue::ArenaDtor(void* object) {
  Extras_IMUValue* _this = reinterpret_cast< Extras_IMUValue* >(object);
  (void)_this;
}
void Extras_IMUValue::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_IMUValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_IMUValue& Extras_IMUValue::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_IMUValue_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_IMUValue::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.IMUValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_IMUValue::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_IMUValue::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.IMUValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float z = 3;
  if (!(this->z() <= 0 && this->z() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.IMUValue)
  return target;
}

size_t Extras_IMUValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.IMUValue)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    total_size += 1 + 4;
  }

  // float y = 2;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    total_size += 1 + 4;
  }

  // float z = 3;
  if (!(this->z() <= 0 && this->z() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_IMUValue::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.IMUValue)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_IMUValue* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_IMUValue>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.IMUValue)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.IMUValue)
    MergeFrom(*source);
  }
}

void Extras_IMUValue::MergeFrom(const Extras_IMUValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.IMUValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.x() <= 0 && from.x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
  if (!(from.y() <= 0 && from.y() >= 0)) {
    _internal_set_y(from._internal_y());
  }
  if (!(from.z() <= 0 && from.z() >= 0)) {
    _internal_set_z(from._internal_z());
  }
}

void Extras_IMUValue::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.IMUValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_IMUValue::CopyFrom(const Extras_IMUValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.IMUValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_IMUValue::IsInitialized() const {
  return true;
}

void Extras_IMUValue::InternalSwap(Extras_IMUValue* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras_IMUValue, z_)
      + sizeof(Extras_IMUValue::z_)
      - PROTOBUF_FIELD_OFFSET(Extras_IMUValue, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_IMUValue::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Extras_TouchInput::InitAsDefaultInstance() {
}
class Extras_TouchInput::_Internal {
 public:
};

Extras_TouchInput::Extras_TouchInput(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.TouchInput)
}
Extras_TouchInput::Extras_TouchInput(const Extras_TouchInput& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&scale_, &from.scale_,
    static_cast<size_t>(reinterpret_cast<char*>(&doubletouch_) -
    reinterpret_cast<char*>(&scale_)) + sizeof(doubletouch_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.TouchInput)
}

void Extras_TouchInput::SharedCtor() {
  ::memset(&scale_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&doubletouch_) -
      reinterpret_cast<char*>(&scale_)) + sizeof(doubletouch_));
}

Extras_TouchInput::~Extras_TouchInput() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.TouchInput)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_TouchInput::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Extras_TouchInput::ArenaDtor(void* object) {
  Extras_TouchInput* _this = reinterpret_cast< Extras_TouchInput* >(object);
  (void)_this;
}
void Extras_TouchInput::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_TouchInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_TouchInput& Extras_TouchInput::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_TouchInput_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_TouchInput::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.TouchInput)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&scale_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&doubletouch_) -
      reinterpret_cast<char*>(&scale_)) + sizeof(doubletouch_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_TouchInput::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float scale = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          scale_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float x = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21)) {
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float y = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29)) {
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // bool doubleTouch = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          doubletouch_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_TouchInput::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.TouchInput)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float scale = 1;
  if (!(this->scale() <= 0 && this->scale() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_scale(), target);
  }

  // float x = 2;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(2, this->_internal_x(), target);
  }

  // float y = 3;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(3, this->_internal_y(), target);
  }

  // bool doubleTouch = 4;
  if (this->doubletouch() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_doubletouch(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.TouchInput)
  return target;
}

size_t Extras_TouchInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.TouchInput)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float scale = 1;
  if (!(this->scale() <= 0 && this->scale() >= 0)) {
    total_size += 1 + 4;
  }

  // float x = 2;
  if (!(this->x() <= 0 && this->x() >= 0)) {
    total_size += 1 + 4;
  }

  // float y = 3;
  if (!(this->y() <= 0 && this->y() >= 0)) {
    total_size += 1 + 4;
  }

  // bool doubleTouch = 4;
  if (this->doubletouch() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_TouchInput::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.TouchInput)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_TouchInput* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_TouchInput>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.TouchInput)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.TouchInput)
    MergeFrom(*source);
  }
}

void Extras_TouchInput::MergeFrom(const Extras_TouchInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.TouchInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.scale() <= 0 && from.scale() >= 0)) {
    _internal_set_scale(from._internal_scale());
  }
  if (!(from.x() <= 0 && from.x() >= 0)) {
    _internal_set_x(from._internal_x());
  }
  if (!(from.y() <= 0 && from.y() >= 0)) {
    _internal_set_y(from._internal_y());
  }
  if (from.doubletouch() != 0) {
    _internal_set_doubletouch(from._internal_doubletouch());
  }
}

void Extras_TouchInput::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.TouchInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_TouchInput::CopyFrom(const Extras_TouchInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.TouchInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_TouchInput::IsInitialized() const {
  return true;
}

void Extras_TouchInput::InternalSwap(Extras_TouchInput* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras_TouchInput, doubletouch_)
      + sizeof(Extras_TouchInput::doubletouch_)
      - PROTOBUF_FIELD_OFFSET(Extras_TouchInput, scale_)>(
          reinterpret_cast<char*>(&scale_),
          reinterpret_cast<char*>(&other->scale_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_TouchInput::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Extras_ScreenValue::InitAsDefaultInstance() {
}
class Extras_ScreenValue::_Internal {
 public:
};

Extras_ScreenValue::Extras_ScreenValue(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.ScreenValue)
}
Extras_ScreenValue::Extras_ScreenValue(const Extras_ScreenValue& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&ratio_, &from.ratio_,
    static_cast<size_t>(reinterpret_cast<char*>(&resolution_) -
    reinterpret_cast<char*>(&ratio_)) + sizeof(resolution_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.ScreenValue)
}

void Extras_ScreenValue::SharedCtor() {
  ::memset(&ratio_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resolution_) -
      reinterpret_cast<char*>(&ratio_)) + sizeof(resolution_));
}

Extras_ScreenValue::~Extras_ScreenValue() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.ScreenValue)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_ScreenValue::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Extras_ScreenValue::ArenaDtor(void* object) {
  Extras_ScreenValue* _this = reinterpret_cast< Extras_ScreenValue* >(object);
  (void)_this;
}
void Extras_ScreenValue::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_ScreenValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_ScreenValue& Extras_ScreenValue::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_ScreenValue_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_ScreenValue::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.ScreenValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&ratio_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&resolution_) -
      reinterpret_cast<char*>(&ratio_)) + sizeof(resolution_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_ScreenValue::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // float ratio = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          ratio_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // int32 resolution = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          resolution_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_ScreenValue::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.ScreenValue)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float ratio = 1;
  if (!(this->ratio() <= 0 && this->ratio() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(1, this->_internal_ratio(), target);
  }

  // int32 resolution = 2;
  if (this->resolution() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_resolution(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.ScreenValue)
  return target;
}

size_t Extras_ScreenValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.ScreenValue)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float ratio = 1;
  if (!(this->ratio() <= 0 && this->ratio() >= 0)) {
    total_size += 1 + 4;
  }

  // int32 resolution = 2;
  if (this->resolution() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_resolution());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_ScreenValue::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.ScreenValue)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_ScreenValue* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_ScreenValue>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.ScreenValue)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.ScreenValue)
    MergeFrom(*source);
  }
}

void Extras_ScreenValue::MergeFrom(const Extras_ScreenValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.ScreenValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!(from.ratio() <= 0 && from.ratio() >= 0)) {
    _internal_set_ratio(from._internal_ratio());
  }
  if (from.resolution() != 0) {
    _internal_set_resolution(from._internal_resolution());
  }
}

void Extras_ScreenValue::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.ScreenValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_ScreenValue::CopyFrom(const Extras_ScreenValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.ScreenValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_ScreenValue::IsInitialized() const {
  return true;
}

void Extras_ScreenValue::InternalSwap(Extras_ScreenValue* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras_ScreenValue, resolution_)
      + sizeof(Extras_ScreenValue::resolution_)
      - PROTOBUF_FIELD_OFFSET(Extras_ScreenValue, ratio_)>(
          reinterpret_cast<char*>(&ratio_),
          reinterpret_cast<char*>(&other->ratio_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_ScreenValue::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Extras_ArrowKey::InitAsDefaultInstance() {
}
class Extras_ArrowKey::_Internal {
 public:
};

Extras_ArrowKey::Extras_ArrowKey(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.ArrowKey)
}
Extras_ArrowKey::Extras_ArrowKey(const Extras_ArrowKey& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&left_, &from.left_,
    static_cast<size_t>(reinterpret_cast<char*>(&down_) -
    reinterpret_cast<char*>(&left_)) + sizeof(down_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.ArrowKey)
}

void Extras_ArrowKey::SharedCtor() {
  ::memset(&left_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&down_) -
      reinterpret_cast<char*>(&left_)) + sizeof(down_));
}

Extras_ArrowKey::~Extras_ArrowKey() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.ArrowKey)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_ArrowKey::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Extras_ArrowKey::ArenaDtor(void* object) {
  Extras_ArrowKey* _this = reinterpret_cast< Extras_ArrowKey* >(object);
  (void)_this;
}
void Extras_ArrowKey::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_ArrowKey::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_ArrowKey& Extras_ArrowKey::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_ArrowKey_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_ArrowKey::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.ArrowKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&left_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&down_) -
      reinterpret_cast<char*>(&left_)) + sizeof(down_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_ArrowKey::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool left = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          left_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool right = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          right_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool up = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          up_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool down = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          down_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_ArrowKey::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.ArrowKey)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool left = 1;
  if (this->left() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_left(), target);
  }

  // bool right = 2;
  if (this->right() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_right(), target);
  }

  // bool up = 3;
  if (this->up() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_up(), target);
  }

  // bool down = 4;
  if (this->down() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_down(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.ArrowKey)
  return target;
}

size_t Extras_ArrowKey::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.ArrowKey)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool left = 1;
  if (this->left() != 0) {
    total_size += 1 + 1;
  }

  // bool right = 2;
  if (this->right() != 0) {
    total_size += 1 + 1;
  }

  // bool up = 3;
  if (this->up() != 0) {
    total_size += 1 + 1;
  }

  // bool down = 4;
  if (this->down() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_ArrowKey::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.ArrowKey)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_ArrowKey* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_ArrowKey>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.ArrowKey)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.ArrowKey)
    MergeFrom(*source);
  }
}

void Extras_ArrowKey::MergeFrom(const Extras_ArrowKey& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.ArrowKey)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.left() != 0) {
    _internal_set_left(from._internal_left());
  }
  if (from.right() != 0) {
    _internal_set_right(from._internal_right());
  }
  if (from.up() != 0) {
    _internal_set_up(from._internal_up());
  }
  if (from.down() != 0) {
    _internal_set_down(from._internal_down());
  }
}

void Extras_ArrowKey::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.ArrowKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_ArrowKey::CopyFrom(const Extras_ArrowKey& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.ArrowKey)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_ArrowKey::IsInitialized() const {
  return true;
}

void Extras_ArrowKey::InternalSwap(Extras_ArrowKey* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras_ArrowKey, down_)
      + sizeof(Extras_ArrowKey::down_)
      - PROTOBUF_FIELD_OFFSET(Extras_ArrowKey, left_)>(
          reinterpret_cast<char*>(&left_),
          reinterpret_cast<char*>(&other->left_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_ArrowKey::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Extras_Setting::InitAsDefaultInstance() {
}
class Extras_Setting::_Internal {
 public:
};

Extras_Setting::Extras_Setting(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras.Setting)
}
Extras_Setting::Extras_Setting(const Extras_Setting& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&scene_, &from.scene_,
    static_cast<size_t>(reinterpret_cast<char*>(&info_) -
    reinterpret_cast<char*>(&scene_)) + sizeof(info_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras.Setting)
}

void Extras_Setting::SharedCtor() {
  ::memset(&scene_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&info_) -
      reinterpret_cast<char*>(&scene_)) + sizeof(info_));
}

Extras_Setting::~Extras_Setting() {
  // @@protoc_insertion_point(destructor:openfluid.Extras.Setting)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras_Setting::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void Extras_Setting::ArenaDtor(void* object) {
  Extras_Setting* _this = reinterpret_cast< Extras_Setting* >(object);
  (void)_this;
}
void Extras_Setting::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras_Setting::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras_Setting& Extras_Setting::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_Setting_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras_Setting::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras.Setting)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&scene_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&info_) -
      reinterpret_cast<char*>(&scene_)) + sizeof(info_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras_Setting::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // int32 scene = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          scene_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool align_center = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          align_center_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ar_view = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ar_view_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool reset = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          reset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool pause = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          pause_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool particle = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 48)) {
          particle_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool info = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          info_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras_Setting::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras.Setting)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 scene = 1;
  if (this->scene() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_scene(), target);
  }

  // bool align_center = 2;
  if (this->align_center() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_align_center(), target);
  }

  // bool ar_view = 3;
  if (this->ar_view() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_ar_view(), target);
  }

  // bool reset = 4;
  if (this->reset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_reset(), target);
  }

  // bool pause = 5;
  if (this->pause() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_pause(), target);
  }

  // bool particle = 6;
  if (this->particle() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(6, this->_internal_particle(), target);
  }

  // bool info = 7;
  if (this->info() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_info(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras.Setting)
  return target;
}

size_t Extras_Setting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras.Setting)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 scene = 1;
  if (this->scene() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_scene());
  }

  // bool align_center = 2;
  if (this->align_center() != 0) {
    total_size += 1 + 1;
  }

  // bool ar_view = 3;
  if (this->ar_view() != 0) {
    total_size += 1 + 1;
  }

  // bool reset = 4;
  if (this->reset() != 0) {
    total_size += 1 + 1;
  }

  // bool pause = 5;
  if (this->pause() != 0) {
    total_size += 1 + 1;
  }

  // bool particle = 6;
  if (this->particle() != 0) {
    total_size += 1 + 1;
  }

  // bool info = 7;
  if (this->info() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras_Setting::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras.Setting)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras_Setting* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras_Setting>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras.Setting)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras.Setting)
    MergeFrom(*source);
  }
}

void Extras_Setting::MergeFrom(const Extras_Setting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras.Setting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.scene() != 0) {
    _internal_set_scene(from._internal_scene());
  }
  if (from.align_center() != 0) {
    _internal_set_align_center(from._internal_align_center());
  }
  if (from.ar_view() != 0) {
    _internal_set_ar_view(from._internal_ar_view());
  }
  if (from.reset() != 0) {
    _internal_set_reset(from._internal_reset());
  }
  if (from.pause() != 0) {
    _internal_set_pause(from._internal_pause());
  }
  if (from.particle() != 0) {
    _internal_set_particle(from._internal_particle());
  }
  if (from.info() != 0) {
    _internal_set_info(from._internal_info());
  }
}

void Extras_Setting::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras.Setting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras_Setting::CopyFrom(const Extras_Setting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras.Setting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras_Setting::IsInitialized() const {
  return true;
}

void Extras_Setting::InternalSwap(Extras_Setting* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras_Setting, info_)
      + sizeof(Extras_Setting::info_)
      - PROTOBUF_FIELD_OFFSET(Extras_Setting, scene_)>(
          reinterpret_cast<char*>(&scene_),
          reinterpret_cast<char*>(&other->scene_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras_Setting::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

Extras_StyleListEntry_DoNotUse::Extras_StyleListEntry_DoNotUse() {}
Extras_StyleListEntry_DoNotUse::Extras_StyleListEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void Extras_StyleListEntry_DoNotUse::MergeFrom(const Extras_StyleListEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata Extras_StyleListEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void Extras_StyleListEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void Extras::InitAsDefaultInstance() {
  ::openfluid::_Extras_default_instance_._instance.get_mutable()->imu_value_ = const_cast< ::openfluid::Extras_IMUValue*>(
      ::openfluid::Extras_IMUValue::internal_default_instance());
  ::openfluid::_Extras_default_instance_._instance.get_mutable()->screen_value_ = const_cast< ::openfluid::Extras_ScreenValue*>(
      ::openfluid::Extras_ScreenValue::internal_default_instance());
  ::openfluid::_Extras_default_instance_._instance.get_mutable()->touch_value_ = const_cast< ::openfluid::Extras_TouchInput*>(
      ::openfluid::Extras_TouchInput::internal_default_instance());
  ::openfluid::_Extras_default_instance_._instance.get_mutable()->arrow_key_ = const_cast< ::openfluid::Extras_ArrowKey*>(
      ::openfluid::Extras_ArrowKey::internal_default_instance());
  ::openfluid::_Extras_default_instance_._instance.get_mutable()->setting_value_ = const_cast< ::openfluid::Extras_Setting*>(
      ::openfluid::Extras_Setting::internal_default_instance());
}
class Extras::_Internal {
 public:
  static const ::openfluid::Extras_IMUValue& imu_value(const Extras* msg);
  static const ::openfluid::Extras_ScreenValue& screen_value(const Extras* msg);
  static const ::openfluid::Extras_TouchInput& touch_value(const Extras* msg);
  static const ::openfluid::Extras_ArrowKey& arrow_key(const Extras* msg);
  static const ::openfluid::Extras_Setting& setting_value(const Extras* msg);
};

const ::openfluid::Extras_IMUValue&
Extras::_Internal::imu_value(const Extras* msg) {
  return *msg->imu_value_;
}
const ::openfluid::Extras_ScreenValue&
Extras::_Internal::screen_value(const Extras* msg) {
  return *msg->screen_value_;
}
const ::openfluid::Extras_TouchInput&
Extras::_Internal::touch_value(const Extras* msg) {
  return *msg->touch_value_;
}
const ::openfluid::Extras_ArrowKey&
Extras::_Internal::arrow_key(const Extras* msg) {
  return *msg->arrow_key_;
}
const ::openfluid::Extras_Setting&
Extras::_Internal::setting_value(const Extras* msg) {
  return *msg->setting_value_;
}
Extras::Extras(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  style_list_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:openfluid.Extras)
}
Extras::Extras(const Extras& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  style_list_.MergeFrom(from.style_list_);
  if (from._internal_has_imu_value()) {
    imu_value_ = new ::openfluid::Extras_IMUValue(*from.imu_value_);
  } else {
    imu_value_ = nullptr;
  }
  if (from._internal_has_screen_value()) {
    screen_value_ = new ::openfluid::Extras_ScreenValue(*from.screen_value_);
  } else {
    screen_value_ = nullptr;
  }
  if (from._internal_has_touch_value()) {
    touch_value_ = new ::openfluid::Extras_TouchInput(*from.touch_value_);
  } else {
    touch_value_ = nullptr;
  }
  if (from._internal_has_arrow_key()) {
    arrow_key_ = new ::openfluid::Extras_ArrowKey(*from.arrow_key_);
  } else {
    arrow_key_ = nullptr;
  }
  if (from._internal_has_setting_value()) {
    setting_value_ = new ::openfluid::Extras_Setting(*from.setting_value_);
  } else {
    setting_value_ = nullptr;
  }
  ::memcpy(&latency_token_, &from.latency_token_,
    static_cast<size_t>(reinterpret_cast<char*>(&fps_) -
    reinterpret_cast<char*>(&latency_token_)) + sizeof(fps_));
  // @@protoc_insertion_point(copy_constructor:openfluid.Extras)
}

void Extras::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Extras_openfluid_2eproto.base);
  ::memset(&imu_value_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fps_) -
      reinterpret_cast<char*>(&imu_value_)) + sizeof(fps_));
}

Extras::~Extras() {
  // @@protoc_insertion_point(destructor:openfluid.Extras)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Extras::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete imu_value_;
  if (this != internal_default_instance()) delete screen_value_;
  if (this != internal_default_instance()) delete touch_value_;
  if (this != internal_default_instance()) delete arrow_key_;
  if (this != internal_default_instance()) delete setting_value_;
}

void Extras::ArenaDtor(void* object) {
  Extras* _this = reinterpret_cast< Extras* >(object);
  (void)_this;
}
void Extras::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Extras::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Extras& Extras::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Extras_openfluid_2eproto.base);
  return *internal_default_instance();
}


void Extras::Clear() {
// @@protoc_insertion_point(message_clear_start:openfluid.Extras)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  style_list_.Clear();
  if (GetArena() == nullptr && imu_value_ != nullptr) {
    delete imu_value_;
  }
  imu_value_ = nullptr;
  if (GetArena() == nullptr && screen_value_ != nullptr) {
    delete screen_value_;
  }
  screen_value_ = nullptr;
  if (GetArena() == nullptr && touch_value_ != nullptr) {
    delete touch_value_;
  }
  touch_value_ = nullptr;
  if (GetArena() == nullptr && arrow_key_ != nullptr) {
    delete arrow_key_;
  }
  arrow_key_ = nullptr;
  if (GetArena() == nullptr && setting_value_ != nullptr) {
    delete setting_value_;
  }
  setting_value_ = nullptr;
  ::memset(&latency_token_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fps_) -
      reinterpret_cast<char*>(&latency_token_)) + sizeof(fps_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Extras::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // map<string, string> style_list = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&style_list_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      // .openfluid.Extras.IMUValue imu_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_imu_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .openfluid.Extras.ScreenValue screen_value = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_screen_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .openfluid.Extras.TouchInput touch_value = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_touch_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .openfluid.Extras.ArrowKey arrow_key = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_arrow_key(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .openfluid.Extras.Setting setting_value = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_setting_value(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool latency_token = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          latency_token_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 fps = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          fps_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Extras::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:openfluid.Extras)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> style_list = 1;
  if (!this->_internal_style_list().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "openfluid.Extras.StyleListEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "openfluid.Extras.StyleListEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_style_list().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_style_list().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_style_list().begin();
          it != this->_internal_style_list().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = Extras_StyleListEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_style_list().begin();
          it != this->_internal_style_list().end(); ++it) {
        target = Extras_StyleListEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  // .openfluid.Extras.IMUValue imu_value = 2;
  if (this->has_imu_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::imu_value(this), target, stream);
  }

  // .openfluid.Extras.ScreenValue screen_value = 3;
  if (this->has_screen_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::screen_value(this), target, stream);
  }

  // .openfluid.Extras.TouchInput touch_value = 4;
  if (this->has_touch_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        4, _Internal::touch_value(this), target, stream);
  }

  // .openfluid.Extras.ArrowKey arrow_key = 5;
  if (this->has_arrow_key()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        5, _Internal::arrow_key(this), target, stream);
  }

  // .openfluid.Extras.Setting setting_value = 6;
  if (this->has_setting_value()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::setting_value(this), target, stream);
  }

  // bool latency_token = 7;
  if (this->latency_token() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(7, this->_internal_latency_token(), target);
  }

  // int32 fps = 8;
  if (this->fps() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(8, this->_internal_fps(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:openfluid.Extras)
  return target;
}

size_t Extras::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:openfluid.Extras)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> style_list = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_style_list_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_style_list().begin();
      it != this->_internal_style_list().end(); ++it) {
    total_size += Extras_StyleListEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .openfluid.Extras.IMUValue imu_value = 2;
  if (this->has_imu_value()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *imu_value_);
  }

  // .openfluid.Extras.ScreenValue screen_value = 3;
  if (this->has_screen_value()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *screen_value_);
  }

  // .openfluid.Extras.TouchInput touch_value = 4;
  if (this->has_touch_value()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *touch_value_);
  }

  // .openfluid.Extras.ArrowKey arrow_key = 5;
  if (this->has_arrow_key()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *arrow_key_);
  }

  // .openfluid.Extras.Setting setting_value = 6;
  if (this->has_setting_value()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *setting_value_);
  }

  // bool latency_token = 7;
  if (this->latency_token() != 0) {
    total_size += 1 + 1;
  }

  // int32 fps = 8;
  if (this->fps() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_fps());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Extras::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:openfluid.Extras)
  GOOGLE_DCHECK_NE(&from, this);
  const Extras* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Extras>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:openfluid.Extras)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:openfluid.Extras)
    MergeFrom(*source);
  }
}

void Extras::MergeFrom(const Extras& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:openfluid.Extras)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  style_list_.MergeFrom(from.style_list_);
  if (from.has_imu_value()) {
    _internal_mutable_imu_value()->::openfluid::Extras_IMUValue::MergeFrom(from._internal_imu_value());
  }
  if (from.has_screen_value()) {
    _internal_mutable_screen_value()->::openfluid::Extras_ScreenValue::MergeFrom(from._internal_screen_value());
  }
  if (from.has_touch_value()) {
    _internal_mutable_touch_value()->::openfluid::Extras_TouchInput::MergeFrom(from._internal_touch_value());
  }
  if (from.has_arrow_key()) {
    _internal_mutable_arrow_key()->::openfluid::Extras_ArrowKey::MergeFrom(from._internal_arrow_key());
  }
  if (from.has_setting_value()) {
    _internal_mutable_setting_value()->::openfluid::Extras_Setting::MergeFrom(from._internal_setting_value());
  }
  if (from.latency_token() != 0) {
    _internal_set_latency_token(from._internal_latency_token());
  }
  if (from.fps() != 0) {
    _internal_set_fps(from._internal_fps());
  }
}

void Extras::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:openfluid.Extras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Extras::CopyFrom(const Extras& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:openfluid.Extras)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Extras::IsInitialized() const {
  return true;
}

void Extras::InternalSwap(Extras* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  style_list_.Swap(&other->style_list_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Extras, fps_)
      + sizeof(Extras::fps_)
      - PROTOBUF_FIELD_OFFSET(Extras, imu_value_)>(
          reinterpret_cast<char*>(&imu_value_),
          reinterpret_cast<char*>(&other->imu_value_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Extras::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace openfluid
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::openfluid::Extras_BytesValue* Arena::CreateMaybeMessage< ::openfluid::Extras_BytesValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_BytesValue >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_IMUValue* Arena::CreateMaybeMessage< ::openfluid::Extras_IMUValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_IMUValue >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_TouchInput* Arena::CreateMaybeMessage< ::openfluid::Extras_TouchInput >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_TouchInput >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_ScreenValue* Arena::CreateMaybeMessage< ::openfluid::Extras_ScreenValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_ScreenValue >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_ArrowKey* Arena::CreateMaybeMessage< ::openfluid::Extras_ArrowKey >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_ArrowKey >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_Setting* Arena::CreateMaybeMessage< ::openfluid::Extras_Setting >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_Setting >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras_StyleListEntry_DoNotUse* Arena::CreateMaybeMessage< ::openfluid::Extras_StyleListEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras_StyleListEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::openfluid::Extras* Arena::CreateMaybeMessage< ::openfluid::Extras >(Arena* arena) {
  return Arena::CreateMessageInternal< ::openfluid::Extras >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
